[package]
name = "debug-everything"
version = "0.1.0"
authors = ["main() <main@ehvag.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
